name: GitHub Actions to deploy to org when ever code is merged in main 
run-name: ${{ github.actor }} is running deployment to org using GitHub Actions 🚀
on:
  push:
    branches: 
    - main
jobs:
  Start-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Salesforce CLI
        run: |
          echo Install Salesforce CLI and sfdx-git-delta plugin
          npm install sfdx-cli -g
          echo "y" | sfdx plugins:install sfdx-git-delta
          
      - name: Deploy to Salesforce
        run: |
          echo "Authenticating with Salesforce..."
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > privateKey.key
          sfdx force:auth:jwt:grant -i ${{ secrets.SALESFORCE_CONSUMER_KEY }} -f privateKey.key --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME}} -d -a devjwt
          
          echo "Deploying to Salesforce..."
          sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output "." -i .forceignore
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
          # sfdx force:source:deploy -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --sourcepath tempmanifest --testlevel NoTestRun
          sfdx force:source:deploy -x package/package.xml -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --testlevel NoTestRun
          
          # Check deployment status
          DEPLOY_STATUS=$(sfdx force:source:deploy:report -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} | grep "Status")
          echo "Deployment Status: $DEPLOY_STATUS"