name: GitHub Actions to add logs to test.txt file
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: 
    - main
jobs:
  Write-push-details-on-test-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Salesforce CLI
        run: |
          echo Install Salesforce CLI
          npm install sfdx-cli -g
          echo "y" | sfdx plugins:install sfdx-git-packager
          
      - name: Deploy to Salesforce
        run: |
          echo "Authenticating with Salesforce..."
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > privateKey.key
          sfdx force:auth:jwt:grant -i ${{ secrets.SALESFORCE_CONSUMER_KEY }} -f privateKey.key --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME}} -d -a devjwt
          
          echo "Deploying to Salesforce..."
          git fetch origin "+refs/heads/*:refs/remotes/origin/*"
          sfdx git:package -d tempmanifest --targetref=origin/main -f
          sfdx force:source:deploy -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --sourcepath tempmanifest --testlevel NoTestRun
          
          # Check deployment status
          DEPLOY_STATUS=$(sfdx force:source:deploy:report -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} | grep "Status")
          echo "Deployment Status: $DEPLOY_STATUS"